export interface CreateBioData {
  full_name: string;
  date_of_birth: string;
  time_of_birth: string;
  height: string;
  magalik: boolean;
  devak_gotra: string;
  caste_subcaste: string;
  marital_status: string;
  complexion: string;
  education_details: string;
  occupation: string;
  hobbies: string;
  gender: string;
  phone_number: string;
  city: string;
  state: string;
  slug: string;
  place_of_birth: string;
  rashi: string;
  nakshatram: string;
  color: string;
  job: string;
  salary: string;
  native_place: string;
  father_name: string;
  mother_name: string;
  sibling_details: string;
  documents: string | string[];
  user_id: string;
}
